apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: development-apps
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: development-apps
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 9090
      targetPort: 9090