apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: development-apps
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: development-apps
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086